name: Docker Image CI

on:
  push:
    branches: [ "main" ]  
  workflow_dispatch:

jobs:
  build_site:
    name: build the ng site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: |
            dist/
            Dockerfile

  build_and_push_image_to_registry:  
    name: push image to registry
    needs: build_site
    runs-on: ubuntu-latest
    steps:  
    - uses: actions/download-artifact@v3
      with:
        name: dist
      env:
        DOCKER_REGISTRY: registry.digitalocean.com
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag $DOCKER_REGISTRY/kevcoder/kevcoder.com
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login $DOCKER_REGISTRY --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push $DOCKER_REGISTRY/kevcoder/kevcoder.com
        docker logout $DOCKER_REGISTRY
