name: Docker Image CI

on:
  push:
    branches: [ "main" ]  
  workflow_dispatch:

jobs:

  build:
    name: push to digital ocean registry
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag registry.digitalocean.com/kevcoder/kevcoder.com:$(date +%s)
        docker login registry.digitalocean.com --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
        docker push registry.digitalocean.com/kevcoder/kevcoder.com
