name: Docker Image CI

on:
  push:
    branches: [ "main" ]  
  workflow_dispatch:

jobs:
  build_site:
    name: build the ng site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: build_output
          path: dist/**

  build_and_push_image_to_registry:  
    name: push image to registry
    needs: build_site
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: build_output
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag registry.digitalocean.com/kevcoder/kevcoder.com:$(date +%s)
        docker login registry.digitalocean.com --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
        docker push registry.digitalocean.com/kevcoder/kevcoder.com
